### PR TITLE
Extend the definition of equality in the `isSamePerson` method.

### LINKED ISSUE #90: Allow adding duplicate persons
Currently, Survin does not allow users to `add` people with the same name. For example,
```
add n/John Doe ... s/Shopping survey
> New person added: John Doe ...

add n/John Doe ... s/Academic survey
> (ERROR) This person already exists in the address book
```
This probably contradicts the purpose of Survin, since it is possible to have the same person participate in different surveys. 

As a fix, I suggest we change the definition of `isSamePerson` in the `Person` class. As of now, this method only checks if the names are equal.
```Java
public boolean isSamePerson(Person otherPerson) {
    if (otherPerson == this) {
        return true;
    }

    return otherPerson != null
            && otherPerson.getName().equals(getName());
}
```
Instead, on top of checking equality of `getName()`, we could also check equality of `getSurvey()`, so that we have

```
add n/John Doe ... s/Shopping survey
> New person added: John Doe ... Survey: Shopping survey

add n/John Doe ... s/Academic survey
> New person added: John Doe ... Survey: Academic survey

add n/John Doe ... s/Shopping survey
> (ERROR) This person already exists in the address book
```

as intended. Is this a sufficient fix? I'm unsure if there are other edge cases I've yet to consider.

If this change is alright with everyone, I'll be glad to open a PR.

### PR DESCRIPTION
**Pull request by ryanlml**
Fixes #90. Implemented changes as suggested by the team; thanks for everyone's input.

Change from checking equality of name to checking equality of name, phone number, email and survey. Checks are case sensitive.

Update `PersonTest` to adapt to the new functionality of `isSamePerson`, along with more tests.

### CODE REVIEW

**Review by KeithPJX — DISMISSED** [review]
LGTM. Thanks for the changes. Some checkstyle problems to change I think.

**Comment by KeithPJX** [comment]
@ryanlml you can try these steps to configure your import format, if you have not done so yet. It stops IntelliJ from automatically doing a wildcard import once a certain number of import from the package happens.
https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-import-order

**Comment by ryanlml** [comment]
> @ryanlml you can try these steps to configure your import format, if you have not done so yet. It stops IntelliJ from automatically doing a wildcard import once a certain number of import from the package happens.
> https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-import-order

Thanks for the suggestion! I've changed the settings accordingly, it works wonders now.

**Review by KeithPJX — APPROVED** [review]
LTGM. Thanks for the changes.

**Pull request merged**
