### PR TITLE
Add DeveloperGuide for `delete`

### PR DESCRIPTION
**Pull request by deepimpactmir**
Will add some diagrams for completeness.

### CODE REVIEW

**Review by KeithPJX — APPROVED** [review]
LGTM! I think your linter made a lot of changes.

**Comment by deepimpactmir** [comment]
Yeah. I think the markdown that AB3 uses is a bit old? Not too sure

**Comment by KeithPJX** [comment]
I think there is a problem with the sequence diagram. The lifeline of the DeleteCommandParser should end on the 'X'.

**Comment by deepimpactmir** [comment]
Mm. If i recall correctly, i think it's a quirk of PlantUML. See this diagram in Developer Guide for AB3

image

**Comment by KeithPJX** [comment]
Oh okay, then it should be fine. Thanks!

**Pull request merged**
